# Generated by Django 5.2.8 on 2025-11-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('PROCESADO', 'Procesado')], default='ENVIADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
