# Generated by Django 5.2.8 on 2025-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reportediario_estado_alter_reportediario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('PROCESADO', 'Procesado'), ('RECHAZADO', 'Rechazado')], default='ENVIADO', max_length=50),
        ),
    ]
