# Generated by Django 5.2.8 on 2025-11-11 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reportediario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choferes', to='reportes.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('patente', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=50)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camiones', to='reportes.centro')),
                ('chofer_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.chofer')),
            ],
        ),
    ]
