# Generated by Django 5.2.8 on 2025-11-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_chofer_camion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('PROCESADO', 'Procesado'), ('RECHAZADO', 'Rechazado')], default='PROCESADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('DIRECTOR', 'Director General'), ('OPERACIONES', 'Jefe de Operaciones'), ('ADMIN', 'Administrador Centro')], default='ADMIN', max_length=50),
        ),
    ]
