# Generated by Django 4.2.14 on 2025-11-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_reportediario_estado_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('DIRECTOR', 'Director General'), ('OPERACIONES', 'Jefe de Operaciones'), ('ADMIN', 'Administrador Centro'), ('FINANZAS', 'Área Financiera')], default='ADMIN', max_length=50),
        ),
    ]
